# Global Configuration
global:
  namespace: ollama-stack
  
# Infrastructure Configuration
infrastructure:
  storage:
    customClass:
      enabled: true
      name: "evo4t-storage"
      path: "/mnt/evo4t/microk8s-storage"
      reclaimPolicy: "Retain"
      setAsDefault: true

# Networking Configuration
networking:
  metallb:
    enabled: true
    ipPool:
      name: "ollama-ip-pool"
      addresses: "192.168.1.100-192.168.1.110"
  services:
    openwebui:
      ip: "192.168.1.101"
      port: 8080
    grafana:
      ip: "192.168.1.102"
      port: 3000
# Ollama Configuration
ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "16Gi"
      cpu: "4000m"
    limits:
      memory: "64Gi"
      cpu: "20000m"
  persistence:
    enabled: true
    size: 1Ti
    storageClass: "evo4t-storage"
  
  # Ollama-specific settings
  config:
    host: "0.0.0.0"
    numParallel: 4
    maxLoadedModels: 2
    flashAttention: true
  
  # Graceful shutdown settings
  terminationGracePeriodSeconds: 60

# OpenWebUI Configuration
openwebui:
  enabled: true
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: main
    pullPolicy: IfNotPresent
  
  auth:
    enabled: true
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "evo4t-storage"

# Monitoring Configuration
monitoring:
  grafana:
    externalAccess:
      enabled: true
      namespace: "observability"
      serviceName: "grafana-external"
    selector:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: kube-prom-stack
  
  prometheus:
    serviceMonitor:
      enabled: true
      endpoints:
        - port: "http"
          interval: "30s"
          path: "/metrics"

# Development/Debug Settings
debug:
  enabled: true
  verbose: false

# System-specific configuration for dlogan-ai-series
# Hardware: AMD Ryzen AI 9 HX 370, 96GB RAM
# Storage: 1TB mounted at /mnt/evo4t
# Network: 192.168.1.x with MetalLB range 100-110
# Project Directory: /home/dlogan/ai
