{{- if and .Values.ollama.enabled .Values.ollama.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ollama-stack.labels" . | nindent 4 }}
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
  storageClassName: {{ .Values.ollama.persistence.storageClass }}
{{- end }}
