{{- if .Values.openwebui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ollama-stack.labels" . | nindent 4 }}
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ollama-stack.selectorLabels" . | nindent 6 }}
      app: open-webui
  template:
    metadata:
      labels:
        {{- include "ollama-stack.selectorLabels" . | nindent 8 }}
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: {{ .Values.openwebui.image.repository }}:{{ .Values.openwebui.image.tag }}
        imagePullPolicy: {{ .Values.openwebui.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service.{{ .Values.global.namespace }}.svc.cluster.local:11434"
        - name: WEBUI_AUTH
          value: {{ .Values.openwebui.auth.enabled | quote }}
        resources:
          {{- toYaml .Values.openwebui.resources | nindent 10 }}
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: open-webui-data
        {{- if .Values.openwebui.persistence.enabled }}
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
{{- end }}
