# metallb-l2-advertisement.yaml
# This manifest explicitly tells MetalLB which network interface to use
# AND which IP address pool to announce for.

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-advertisement
  namespace: metallb-system
spec:
  # This selector explicitly links this advertisement to our IP pool.
  ipAddressPools:
  - default-pool
  # This forces it to use only your physical LAN interface.
  interfaces:
  - enp195s0


