# ollama-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ollama-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi

