# open-webui-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
  namespace: ollama-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

